# CDI TCK configuration - Syringe porting package
org.jboss.cdi.tck.spi.Beans=com.threeamigos.common.util.implementations.injection.arquillian.tck.SyringeBeansImpl
org.jboss.cdi.tck.spi.Contexts=com.threeamigos.common.util.implementations.injection.arquillian.tck.SyringeContextsImpl
org.jboss.cdi.tck.spi.EL=com.threeamigos.common.util.implementations.injection.arquillian.tck.SyringeELImpl
org.jboss.cdi.tck.spi.CreationalContexts=com.threeamigos.common.util.implementations.injection.arquillian.tck.SyringeCreationalContextsImpl
org.jboss.cdi.tck.spi.Contextuals=com.threeamigos.common.util.implementations.injection.arquillian.tck.SyringeContextualsImpl
